### PR TITLE
fix(home): Use Discord for signups

### PR DESCRIPTION
**Pull request by cr03**
Also change content related to slack

and comment out the list of channels for now until we figure out how to direct link to discord channels if possible

### CODE REVIEW

**Comment by cr03** [comment]
Ok, tested it out locally. Found two unrelated issues. Everything else appears to be good to go!

**Comment by ahmadnassri** [comment]
don't think those emails are functional ...

**Comment by cr03** [comment]
Ah ok well this might be useful... wanna go this route?

https://support.discord.com/hc/en-us/community/posts/360037884532/comments/360010916271

> As repeatedly tested https://discordapp.com/users/USERID works as long as the user you're trying to contact allows being messaged by people off their friend list :) No need to be friends or share a server as long as you mark it so in your settings!

**Comment by ahmadnassri** [comment]
yes, better do that path.

**Comment by cr03** [comment]
Testing these out here for a minute, none of them seem to be working for me yet. 

https://discordapp.com/channels/@me/ahmadnassri
https://discordapp.com/channels/@me/Scorandum

https://discordapp.com/users/ahmadnassri
https://discordapp.com/users/Scorandum

https://discordapp.com/channels/@me/ahmadnassri#8773
https://discordapp.com/channels/@me/Scorandum#0643

https://discordapp.com/users/ahmadnassri#8773
https://discordapp.com/users/Scorandum#0643

**Comment by cr03** [comment]
https://support.discord.com/hc/en-us/community/posts/360041519131/comments/4420092543383

>    Settings > Advanced > Developer Mode [ON]
>    Go to a chat with your message
>    Right-click on your profile picture beside your message
>    Copy ID
>    Your profile URL will thus be:
>
 >   https://discord.com/users/profile_id

>    where `profile_id` is the part you just copied


  (these IDs are available to anyone)

Ahmad: https://discordapp.com/users/292713944060002315
Andrew: https://discordapp.com/users/172908093150068736

Now **here's the only problem** -- these links don't work if you "Open In App" which of course most people will do.
They do work if you open them in web.

Sooooooo, crud.

What would you prefer to do instead?

**Pull request merged**
